export const responseTracker = {
  questions: [1, 2, 3, 4],
  answerDetail: {
    1: {
      title: 'Question 1',
      fileName: 'question_1.webm',
      blobName: 'question_1.webm',
      status: 'UPLOADED',
      stage: 'VIDEO',
      uploaded: 100,
      messageKey: 'Uploaded',
      questionId: '1',
      messageValue: null,
      failedCount: 0,
      isRetry: false,
    },
    2: {
      title: 'Question 2',
      fileName: 'question_2.webm',
      blobName: 'question_2.webm',
      status: 'ERROR',
      stage: 'VIDEO',
      uploaded: 30,
      messageKey: 'Error',
      questionId: '2',
      messageValue: null,
      failedCount: 0,
      isRetry: false,
    },
    3: {
      title: 'Question 3',
      fileName: 'question_3.webm',
      blobName: 'question_3.webm',
      status: 'ERROR',
      stage: 'VIDEO',
      uploaded: 0,
      messageKey: 'Error',
      questionId: '3',
      messageValue: null,
      failedCount: 0,
      isRetry: false,
    },
    4: {
      title: 'Question 4',
      fileName: 'question_4.webm',
      blobName: 'question_4.webm',
      status: 'UPLOADED',
      stage: 'AUDIO',
      uploaded: 100,
      messageKey: 'Uploaded',
      questionId: '4',
      messageValue: null,
      failedCount: 0,
      isRetry: false,
    },
    5: {
      title: 'Question 5',
      fileName: 'question_5.webm',
      blobName: 'question_5.webm',
      status: 'UPLOADED',
      stage: 'AUDIO',
      uploaded: 100,
      messageKey: 'Uploaded',
      questionId: '5',
      messageValue: null,
      failedCount: 0,
      isRetry: false,
    },
  },
}
